# Configuracion de base de datos (secretos via variables de entorno)
spring.datasource.url=${DB_URL:jdbc:postgresql://db:5432/unsecuredb}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:ChangeMe_UseEnv!}

# Configuracion de la aplicacion
spring.application.name=secure-login
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level.org.springframework.jdbc=INFO
logging.level.com.devsecops=INFO
